library(caTools)
library(data.tree)
library(caret)
library(ggplot2)
library(lattice)
library(rpart.plot)
mushroom <- read.csv("cs358/mushrooms.csv", header = TRUE)
# print(summary(mushroom))
set.seed(105)
sample <- sample.split(mushroom$class, SplitRatio = .80)
library(rpart)
trainingData <- subset(mushroom, sample == TRUE)
testingData <- subset(mushroom, sample == FALSE)

dt.Model      <- rpart( class ~ ., data = trainingData )
cp.optim <- dt.Model$cptable[which.min(dt.Model$cptable[,"xerror"]),"CP"]
dt.Prediction <- predict( dt.Model, newdata = testingData,type ="class" )
print(confusionMatrix(table(dt.Prediction,testingData$class) ))
# rpart.plot(dt.Prediction)
